### ISSUE TITLE
Survive the Supernova

### ISSUE THREAD

**Issue by joshua-smith98** [Raicuparta/ow-mod-db#263]
### Mod uniqueName

Joooosh.SurviveTheSupernova

### Mod name

Survive the Supernova

### GitHub repository URL

https://github.com/joshua-smith98/OW-SurviveTheSupernova

**Comment by Raicuparta** [comment]
@joshua-smith98 Just a couple of notes:
There's [another mod in the database](https://outerwildsmods.com/mods/noend/) that seems to make your mod redundant. I have no problem with this, just thought you should know, in case you wanna try to differentiate it a bit.

It would also be helpful if you changed the "About" section of your github repo, since this is used as the mod description in the website and mod manager. The description should explain what the mod does, instead of why you made the mod.
![image](https://user-images.githubusercontent.com/3955124/165268316-c13b9210-b4c7-4d31-92a5-b63577282218.png)

**Comment by joshua-smith98** [comment]
Thanks! I have changed the repo description. I'll also look into making the readme a bit more descriptive when I get a chance.

I thought someone might've already done this, but I think their mod only disables the ending, whereas mine also disables the SupernovaDestructionVolume so you can survive the blast.
